### ISSUE TITLE
Error while importing Solution

### ISSUE THREAD

**Issue by msvenk** [vgrade/TrackUserLocationinDynamics365AppForPhone#1]
Error occured while importing solutions..

![image](https://user-images.githubusercontent.com/38234007/38532229-2d563f32-3cb7-11e8-9c70-c8105f1b7ac0.png)

**Comment by vgrade** [comment]
I'm updating the solution. will share the updated shortly

**Comment by vgrade** [comment]
msvenk, The import issue has been resolved. Please try importing now.
